# Generated by Django 5.0.6 on 2024-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
